### ISSUE TITLE
Update the Talon firmware

### ISSUE THREAD

**Issue by EvanGebo** [The-Charge/SulfuricAcid2021#2]

**Comment by Shalmezad** [comment]
Latest SRX version is 21.0, can be found here: https://www.ctr-electronics.com/talon-srx.html#product_tabs_technical_resources

**Comment by Shalmezad** [comment]
FX version is 21.0.0.0, can be found here: http://www.ctr-electronics.com/control-system/motor-control/talon-fx.html#product_tabs_technical_resources

**Comment by neuenfeldttj** [comment]
Today, we updated all of the Talons that needed updating.
